file_settings:
  default_input: "../assets/assessments/assessments-****.csv"
  download_files: false
  year_start: 2019 # 2018 has a different format. 
  year_end: 2024
  sql_cache_dir: "../sql_cache"

school_name_translations:
  "Carpenter Elementary School": "Carpenter School"
  "Conant High School": "Conant Middle High School (H)"
  "Jaffrey-Rindge Middle School": "Conant Middle High School (M)"
  "West Running Brook Middle School": "West Running Brook Intermediate School"
  "Allenstown Elementary School": "Allenstown Community School"
  "Armand R. Dupont School": "Allenstown Community School" 