file_settings:
  default_input: "../assets/enrollments/****-School Enrollments by Grade Public.xlsx"
  year_start: "2016"
  year_end: "2025"
  default_output: "output/enrollment_data.sql"
  sql_cache_dir: "../sql_cache"
  
excel_settings:
  data_start_row: 9
  grade_positions:
    PreSchool: 6
    Kindergarten: 7
    "1": 8
    "2": 9
    "3": 10
    "4": 11
    "5": 12
    "6": 13
    "7": 14
    "8": 15
    "9": 16
    "10": 17
    "11": 18
    "12": 19
    "*PG": 20

grade_mappings:
  PreSchool: 1
  Kindergarten: 2
  "1": 3
  "2": 4
  "3": 5
  "4": 6
  "5": 7
  "6": 8
  "7": 9
  "8": 10
  "9": 11
  "10": 12
  "11": 13
  "12": 14
  "*PG": 15
